export interface IUser {
    id?: number,
    firstName?: string,
    lasteName?: string,
    password?: string,
    email?: string,
    isActive?: number,
    deactivatedDate?: string,
    createdAt?: string,
    updatedAt?: string,
    idRole?: number,
    resetToken?: string,
    resetTokenExpiration?: string,
    refreshToken?: string,
}